before_install: cd E:/Avans/Periode1.4/Programmeren4/TentamenProgrammeren/MovieApp
language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "twanvm92-github"
    token:
      secure: "3e0613d813577cce9c841f831bcc112c351558eb"
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'