language: node_js
node_js:
- "stable"
dist: trusty
sudo: required

addons:
  sonarqube:
    organization: "twanvm92-github"
    token:
      secure: "3e0613d813577cce9c841f831bcc112c351558eb"

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

branches:
  only:
  - master
  - develop
  - SonarqubeAndTravis
