before_install: cd ./MovieApp

matrix:
  incude:
    - language: java
      sudo: false
      install: true
      addons:
        sonarqube:
          organization: "twanvm92-github"
          token:
            secure: "3e0613d813577cce9c841f831bcc112c351558eb"
      jdk:
        - oraclejdk8
      script:
        - ./gradlew sonarqube
      cache:
        directories:
          - '$HOME/.m2/repository'
          - '$HOME/.sonar/cache'
          - '$HOME/.gradle'
          - '.gradle'
          
    - language: node_js
      node_js:
    - "stable"
      dist: trusty
      sudo: required

      addons:
        sonarqube:
          organization: "twanvm92-github"
          token:
            secure: "3e0613d813577cce9c841f831bcc112c351558eb"
      jdk:
        - oraclejdk8
      script:
        - sonar-scanner
      cache:
        directories:
          - '$HOME/.sonar/cache'

