language: node_js
node_js:
- "7"
dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8 - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
