language: node_js
node_js:
  - "7"
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8 - g++-4.8
env:
  - CXX=g++-4.8

script: cd NodejsServer && npm install && npm test

deploy:
  provider: heroku
  api_key: 05e0d2a2-7283-40b3-890b-6592c1914afb
  app: programmeren14dag1
  on: develop

cache:
  directories:
    - '$HOME/.sonar/cache'
