language: node_js
node_js:
- "stable"
dist: trusty
sudo: required

addons:
  sonarqube:
    branches :
      - master
      - develop
      - SonarqubeAndTravis
    organization: "twanvm92-github"
    token:
      secure: "3e0613d813577cce9c841f831bcc112c351558eb"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8 - g++-4.8
env:
- CXX=g++-4.8 

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

branches:
  only:
    - master
    - develop
    - SonarqubeAndTravis
